[General]
#################### General ####################
RoundCorners="8"

#################### Background ####################
Background="Backgrounds/abstract-wallpaper.jpg"
# Must be a relative path.
# Supports: png, jpg, jpeg, webp, gif, avi, mp4, mov, mkv, m4v, webm.

#################### Colors ####################

HeaderTextColor="#106363"
DateTextColor="#106363"
TimeTextColor="#6be3e3"

FormBackgroundColor=""
BackgroundColor="#094545"
DimBackgroundColor="#094545"

LoginFieldBackgroundColor="#041616"
PasswordFieldBackgroundColor="#041616"
LoginFieldTextColor="#6be3e3"
PasswordFieldTextColor="#6be3e3"

UserIconColor="#106363"
PasswordIconColor="#106363"
SystemButtonsIconsColor="#106363"
SessionButtonTextColor="#106363"

PlaceholderTextColor="#106363"
WarningColor="#ffffff"

LoginButtonTextColor="#ffffff"
LoginButtonBackgroundColor="#106363"

DropdownTextColor="#ffffff"
DropdownSelectedBackgroundColor="#106363"
DropdownBackgroundColor="#041616"

HighlightTextColor="#041616"
HighlightBackgroundColor="#6be3e3"
HighlightBorderColor="#106363"

HoverUserIconColor="#6be3e3"
HoverPasswordIconColor="#6be3e3"
HoverSystemButtonsIconsColor="#6be3e3"
HoverSessionButtonTextColor="#6be3e3"

#################### Form ####################

FormPosition="left"
# Default: left, Options: left, center, right.

#################### Interface Behavior ####################

HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
# If set to true last successfully logged in user appeares automatically in the username field.
PasswordFocus="true"
# Automaticaly focuses password field.
HideCompletePassword="true"
# Hides the password while typing.
AllowEmptyPassword="false"
# Enable login for users without a password.
AllowUppercaseLettersInUsernames="false"
# Do not change this! Uppercase letters are generally not allowed in usernames. This option is only for systems that differ from this standard!
BypassSystemButtonsChecks="false"
# Skips checking if sddm can perform shutdown, restart, suspend or hibernate, always displays all system buttons.

#################### Translation ####################

# These don't necessarily need to translate anything. You can enter whatever you want here.
TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
